using System.Numerics;
using System.Reflection;

namespace Sonulab.Distill;

/// <summary>The fixed 0.3-RMS drive/reference signal (numpy default_rng(0), 16000
/// samples). Embedded because numpy's PCG64+ziggurat is not portable; generated by
/// tools/distiller/make_cs_fixtures.py on 2026-07-03.</summary>
public static class DriveSignal
{
    private static float[]? _cached;

    public static float[] Get()
    {
        if (_cached is not null) return _cached;
        using var s = Assembly.GetExecutingAssembly()
            .GetManifestResourceStream("Sonulab.Distill.Resources.drive_signal.f32")
            ?? throw new InvalidOperationException("drive_signal.f32 resource missing");
        var bytes = new byte[16000 * 4];
        s.ReadExactly(bytes);
        var x = new float[16000];
        Buffer.BlockCopy(bytes, 0, x, 0, bytes.Length);
        return _cached = x;
    }
}

/// <summary>Wiener–Hammerstein fitter (port of tools/distiller/fit.py). See that
/// file's docstring for the fit-procedure rationale; this port preserves its
/// numerics step for step.</summary>
public static class FirFitter
{
    public const int NTaps = 1024;
    public const int PreZeroTail = 1008;
    public const int NPreShort = 64;
    public const double NlmixMax = 0.7;
    public const double DriveLevel = 0.3;
    public const int NamDefaultSampleRate = 48000;

    public static WhTensors FitWh(INamProcessor model)
    {
        // 1) small-signal linear IR at the device rate
        var ir = Dsp.ToDouble(Probe.LinearIrOfModel(model, n: 8192));
        int sr = model.SampleRate ?? NamDefaultSampleRate;
        if (sr != DeviceSim.SampleRate)
            ir = Resampler.ResamplePoly(ir, DeviceSim.SampleRate, sr);

        // 2) linear cascade split
        var (pre, g2) = DesignLinear(ir);

        // 3) nlmix scalar + output-level calibration at drive level
        var (s, gain) = FitNl(model, pre, g2);
        var g2Cal = Dsp.ToFloat(Dsp.ToDouble(g2).Select(v => v * gain).ToArray());

        return new WhTensors(pre, VxampFormat.G2HeaderFloats(), g2Cal,
                             VxampFormat.NlmixHeaderFloats(), (float)s);
    }

    // ------------------------------------------------------------------ linear

    public static (float[] pre, float[] g2) DesignLinear(double[] irDev)
    {
        var target = irDev[..Math.Min(irDev.Length, 2 * NTaps - 1)];

        // candidate A: delta pre, truncated IR in g2
        var preA = new double[NTaps]; preA[0] = 1.0;
        var g2A = new double[NTaps];
        Array.Copy(target, g2A, Math.Min(target.Length, NTaps));
        double errA = CascadeErr(preA, g2A, target);

        // candidate B: short min-phase pre + deconvolved g2 (VoidX-like split)
        double[] preB, g2B;
        double errB;
        try
        {
            preB = MinphasePre(target);
            g2B = DeconvG2(target, preB);
            errB = CascadeErr(preB, g2B, target);
        }
        catch (ArithmeticException)   // degenerate IR
        {
            preB = preA; g2B = g2A; errB = double.PositiveInfinity;
        }

        var (preD, g2D) = errB < errA ? (preB, g2B) : (preA, g2A);
        var pre = PadTaps(preD);
        for (int i = PreZeroTail; i < NTaps; i++) pre[i] = 0f;   // corpus invariant
        return (pre, PadTaps(g2D));
    }

    private static float[] PadTaps(double[] taps)
    {
        var outT = new float[NTaps];
        for (int i = 0; i < Math.Min(taps.Length, NTaps); i++) outT[i] = (float)taps[i];
        return outT;
    }

    /// <summary>Homomorphic (real-cepstrum) minimum-phase pre: smooth log|H| by low
    /// quefrencies, fold to min phase, exponentiate, truncate to nPre taps.</summary>
    public static double[] MinphasePre(double[] ir, int nPre = NPreShort, int nFft = 8192,
                                       int nLifter = 32)
    {
        var mag = new double[nFft];
        var H = Dsp.Fft(ir, nFft);
        for (int i = 0; i < nFft; i++) mag[i] = Math.Log(Math.Max(H[i].Magnitude, 1e-9));
        var cep = Dsp.Ifft(mag.Select(v => new Complex(v, 0)).ToArray());

        var cepS = new Complex[nFft];
        for (int i = 0; i < nLifter; i++) cepS[i] = cep[i].Real;
        for (int i = nFft - (nLifter - 1); i < nFft; i++) cepS[i] = cep[i].Real;

        var fold = new Complex[nFft];
        fold[0] = cepS[0];
        for (int i = 1; i < nFft / 2; i++) fold[i] = 2.0 * cepS[i];
        fold[nFft / 2] = cepS[nFft / 2];

        var spec = fold.Select(v => v).ToArray();
        MathNet.Numerics.IntegralTransforms.Fourier.Forward(
            spec, MathNet.Numerics.IntegralTransforms.FourierOptions.Matlab);
        for (int i = 0; i < nFft; i++) spec[i] = Complex.Exp(spec[i]);
        var hMin = Dsp.Ifft(spec);
        return hMin.Take(nPre).Select(v => v.Real).ToArray();
    }

    /// <summary>Regularized spectral deconvolution: g2 such that pre ⊛ g2 ≈ target.</summary>
    public static double[] DeconvG2(double[] target, double[] pre, int nOut = NTaps,
                                    double eps = 1e-3)
    {
        int nFft = 1;
        while (nFft < target.Length + nOut) nFft *= 2;
        var T = Dsp.Fft(target, nFft);
        var P = Dsp.Fft(pre, nFft);
        double p2Max = P.Max(c => c.Magnitude * c.Magnitude);
        var G = new Complex[nFft];
        for (int i = 0; i < nFft; i++)
        {
            double p2 = P[i].Magnitude * P[i].Magnitude;
            G[i] = T[i] * Complex.Conjugate(P[i]) / (p2 + eps * p2Max);
        }
        return Dsp.Ifft(G).Take(nOut).Select(v => v.Real).ToArray();
    }

    public static double CascadeErr(double[] pre, double[] g2, double[] target)
    {
        var casc = Dsp.Convolve(pre, g2);
        int n = Math.Max(casc.Length, target.Length);
        var c = new double[n]; casc.CopyTo(c, 0);
        var t = new double[n]; target.CopyTo(t, 0);
        var diff = new double[n];
        for (int i = 0; i < n; i++) diff[i] = c[i] - t[i];
        return Dsp.Norm(diff) / (Dsp.Norm(t) + 1e-12);
    }

    // ------------------------------------------------------------------ nonlinearity

    /// <summary>Run the model on device-rate input, resampling in/out if rates differ
    /// (port of fit._model_ref_at_device_rate — mind the float32 casts at the
    /// model.Process boundary).</summary>
    public static double[] ModelRefAtDeviceRate(INamProcessor model, float[] xDev)
    {
        int sr = model.SampleRate ?? NamDefaultSampleRate;
        if (sr == DeviceSim.SampleRate)
            return Dsp.ToDouble(model.Process(xDev)).Take(xDev.Length).ToArray();
        var xM = Resampler.ResamplePoly(Dsp.ToDouble(xDev), sr, DeviceSim.SampleRate);
        var yM = Dsp.ToDouble(model.Process(Dsp.ToFloat(xM)));
        var y = Resampler.ResamplePoly(yM, DeviceSim.SampleRate, sr);
        var outY = new double[xDev.Length];
        Array.Copy(y, outY, Math.Min(y.Length, outY.Length));
        return outY;
    }

    /// <summary>Grid-fit (nlmix, gain): RMS-matched shape scoring; snaps to exactly 0
    /// when the best nonzero scalar improves the match by less than 0.5%.</summary>
    public static (double nlmix, double gain) FitNl(INamProcessor model, float[] pre, float[] g2)
    {
        var x = DriveSignal.Get();
        var refY = ModelRefAtDeviceRate(model, x);
        double refRms = Dsp.Rms(refY);

        var mid = Dsp.FirFilter(Dsp.ToDouble(pre), Dsp.ToDouble(x));   // stays float64, like fit.py
        var g2D = Dsp.ToDouble(g2);

        (double err, double a) Score(double s)
        {
            var y = Dsp.FirFilter(g2D, Nonlinearity.ApplyNl(mid, s));
            double yRms = Dsp.Rms(y);
            var diff = new double[y.Length];
            if (yRms < 1e-12 || refRms < 1e-12)
            {
                for (int i = 0; i < y.Length; i++) diff[i] = y[i] - refY[i];
                return (Dsp.Norm(diff), 1.0);
            }
            double a = refRms / yRms;
            for (int i = 0; i < y.Length; i++) diff[i] = a * y[i] - refY[i];
            return (Dsp.Norm(diff), a);
        }

        var (e0, a0) = Score(0.0);
        double bestS = 0.0, bestE = e0, bestA = a0;
        for (int i = 1; i <= 70; i++)                     // s = 0.01 .. 0.70 step 0.01
        {
            double s = i * 0.01;
            var (e, a) = Score(s);
            if (e < bestE) { bestS = s; bestE = e; bestA = a; }
        }

        if (bestE > e0 * (1.0 - 0.005)) return (0.0, a0);   // no material nl improvement
        return (bestS, bestA);
    }
}
