using System.Text.Json;

namespace Sonulab.Distill.Tests;

public class ParityTests
{
    private static string Fixture(string name) =>
        Path.Combine(AppContext.BaseDirectory, "fixtures", name);

    private static double RelL2(float[] cs, float[] py)
    {
        double num = 0, den = 0;
        for (int i = 0; i < cs.Length; i++)
        {
            double d = (double)cs[i] - py[i];
            num += d * d;
            den += (double)py[i] * py[i];
        }
        return Math.Sqrt(num) / (Math.Sqrt(den) + 1e-12);
    }

    private static void AssertParity(string label, byte[] csBlob, byte[] pyBlob,
                                     double csErr, double pyErr)
    {
        var cs = VxampCodec.Decode(csBlob);
        var py = VxampCodec.Decode(pyBlob);
        Assert.True(RelL2(cs.PreFir, py.PreFir) <= 1e-3,
            $"{label}: pre_fir relL2 {RelL2(cs.PreFir, py.PreFir):e2}");
        Assert.True(RelL2(cs.G2Fir, py.G2Fir) <= 1e-3,
            $"{label}: g2_fir relL2 {RelL2(cs.G2Fir, py.G2Fir):e2}");
        Assert.Equal(py.G2Header, cs.G2Header);
        Assert.Equal(py.NlmixHeader, cs.NlmixHeader);
        Assert.True(Math.Abs(cs.Nlmix - py.Nlmix) <= 0.010001,
            $"{label}: nlmix cs={cs.Nlmix} py={py.Nlmix}");
        Assert.True(Math.Abs(csErr - pyErr) <= 1e-3,
            $"{label}: our_err cs={csErr:f6} py={pyErr:f6}");
    }

    [Fact]
    public void Synthetic_fixture_matches_python_golden()
    {
        var golden = JsonDocument.Parse(File.ReadAllText(Fixture("golden_metrics.json"))).RootElement;
        Assert.Equal(golden.GetProperty("device_reference_db").GetDouble(),
                     Distiller.DeviceReferenceDb);   // exact — same baked constant

        var csBlob = Distiller.Distill(Fixture("synthetic.nam"));
        var pyBlob = File.ReadAllBytes(Fixture("synthetic.golden.vxamp"));
        var model = NamParser.Load(Fixture("synthetic.nam"));
        double csErr = Fidelity.FidelityVsNam(model, VxampCodec.Decode(csBlob));
        AssertParity("synthetic", csBlob, pyBlob, csErr,
                     golden.GetProperty("our_err").GetDouble());
    }

    [Fact]
    public void Corpus_goldens_match_when_present()
    {
        // Corpus goldens are gitignored (generated by make_cs_fixtures.py --corpus on
        // the corpus machine). Vacuously passes elsewhere — same convention as the
        // Python corpus tests.
        var dir = FindUp("tests/Sonulab.Distill.Tests/goldens-corpus");
        if (dir is null) return;
        var metrics = JsonDocument.Parse(
            File.ReadAllText(Path.Combine(dir, "metrics.json"))).RootElement;

        foreach (var goldenFile in Directory.GetFiles(dir, "*.golden.vxamp"))
        {
            string name = Path.GetFileName(goldenFile).Replace(".golden.vxamp", "");
            string namPath = File.ReadAllText(
                Path.Combine(dir, $"{name}.nam.path.txt")).Trim();
            if (!File.Exists(namPath)) continue;   // corpus moved — skip this pair

            var csBlob = Distiller.Distill(namPath);
            var model = NamParser.Load(namPath);
            double csErr = Fidelity.FidelityVsNam(model, VxampCodec.Decode(csBlob));
            AssertParity(name, csBlob, File.ReadAllBytes(goldenFile), csErr,
                         metrics.GetProperty(name).GetDouble());
        }
    }

    private static string? FindUp(string relative)
    {
        for (var d = new DirectoryInfo(AppContext.BaseDirectory); d is not null; d = d.Parent)
        {
            var candidate = Path.Combine(d.FullName, relative.Replace('/', Path.DirectorySeparatorChar));
            if (Directory.Exists(candidate)) return candidate;
        }
        return null;
    }
}
